# Generated by Django 3.2.5 on 2022-09-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rec', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemlist',
            options={'managed': True},
        ),
    ]
